services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: departments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  service-registry:
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"

  user-service:
    image: user-service
    container_name: user-service
    ports:
      - "8080:8080"

  department-service:
    image: department-service
    container_name: department-service
    ports:
      - "8081:8081"

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "9191:9191"
    depends_on:
      - service-registry
      - user-service
      - department-service

